# .streamlit/secrets.toml

[connections.snowflake]
account = "INCZQMT-SJ68288"
user = "mxtali"
password = "Canelogoat1!"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
